// <auto-generated />
namespace FitnessTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newpropertyaddedtoWorkouttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newpropertyaddedtoWorkouttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907101517462_new-property-added-to-Workout-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
